#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=99
STOP=10

start() {
    echo "Starting AC service"
    # Place commands to start your service here
    # Example: /usr/bin/ac_service start
}

stop() {
    echo "Stopping AC service"
    # Place commands to stop your service here
    # Example: /usr/bin/ac_service stop
}